# Site settings
title: Curiculum Vitae & Portofolio
description: This is web for my Curiculum Vitae and my personal portofolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: M Husni Mubarrok
user_description: A hard worker, honest , tenacious , disciplined , and responsible is the main characteristic of me in the work that I am doing, and is able to work under pressures of working on my own jobs or in jobs that require teamwork, I like new challenges and have a curiosity about new things. the motto of my self that can motivate me is "from now while there is still time" and also "Do the best  of your trust and responsibility with sincerity".
email: mhusnimubarrok@gmail.com
facebook_username: connecting.husni
github_username:  mhusnim
linkedin_username:  mhusnim

# Google-analytics
google-analytics:
  id: ""

show_downloads: true

exclude: ['package.json', 'src' , 'node_modules']
